name: "Audiobook Chapters"
guid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
version: "1.0.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "AudiobookChapters"
category: "Metadata"
description: >
  Extracts chapter and metadata information from sidecar files for audiobooks.
  Supports CUE sheets, OPF (Calibre/EPUB), JSON metadata, NFO (Kodi/XBMC),
  FFmpeg metadata, and simple text files. Also detects multi-file audiobooks
  where each chapter is a separate audio file and creates chapter entries.
artifacts:
  - "Jellyfin.Plugin.AudiobookChapters.dll"
changelog: |
  ## v1.0.0.0
  - Initial release
  - Support for .cue, .opf, .json, .nfo, .ffmetadata, and .txt metadata files
  - Multi-file audiobook detection and chapter creation
  - Configurable metadata source priority
  - Admin configuration page
